{
 "title": "PowerFlow",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PowerFlowValue Distribution  ",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo1\")\n  |> range(start:-1h)\n  |> filter(fn: (r) => r._measurement == \"jsontest\" and r._field == \"PowerFlowValue\")\n  |> group(columns: [\"PowerLineID\"])\n  \n"
    }
   ]
  },
  {
   "title": "PowerFlowValue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo1\")\n  |> range(start:-1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"jsontest\" and\n    (r._field == \"PowerFlowValue\" or \n    r._field == \"PowerLineID\")\n  )"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo1\")\n  |> range(start: -1h)  \n  |> filter(fn: (r) =>  r._measurement == \"jsontest\" and r._field == \"Cluster\")\n  |> group(columns: [\"_field\", \"Cluster\"])\n\n"
    }
   ]
  },
  {
   "title": "CountMin PowerLineID",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo1\")\n  |> range(start:-1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"jsontest\" and\n    (r._field == \"Count_Min\")\n  )"
    }
   ]
  },
  {
   "title": "Flajolet_martin",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo1\")\n  |> range(start:-1h)\n  |> filter(fn: (r) =>\n    r._measurement == \"jsontest\" and\n    (r._field == \"flajolet_martin\")\n  )"
    }
   ]
  }
 ]
}