{
 "title": "Gigi Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Power Flow Values over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jsontest\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"AveragePowerFlow\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Distribution of Power Flow values",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jsontest\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"AveragePowerFlow\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Clustering",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jsontest\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerLineID\" or r[\"_field\"] == \"AveragePowerFlow\" or r[\"_field\"] == \"Cluster\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({_time: r._time, PowerLineID: r.PowerLineID, AveragePowerFlow: r.AveragePowerFlow, Cluster: r.Cluster}))\r\n  |> yield(name: \"result\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo1\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"jsontest\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerLineID\" or r[\"_field\"] == \"AveragePowerFlow\" or r[\"_field\"] == \"Cluster\" or r[\"_field\"] == \"Timestamp\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> filter(fn: (r) => r[\"PowerLineID\"] ==0) \r\n  |> map(fn: (r) => ({_time: r._time, AveragePowerFlow: r.AveragePowerFlow, Cluster: r.Cluster}))\r\n  |> yield(name: \"result\")"
    }
   ]
  }
 ]
}