{
 "title": "New dashboard",
 "time": { "from": "2023-12-09T11:00:00.000Z", "to": "2023-12-13T11:00:00.000Z" },
 "panels": [
  {
   "title": "Weekly Average PowerFlow Value Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "\r\nfrom(bucket: \"Epsymolo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Results\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"WeeklyAveragePowerFlow\")\r\n  |> filter(fn: (r) => r[\"PowerLineID\"] >= \"0.0\")\r\n  |> filter(fn: (r) => r[\"PowerLineID\"] <= \"101.0\")\r\n"
    }
   ]
  },
  {
   "title": "Non-anomalies to anomalies ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Results\" or r[\"_measurement\"] == \"Data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly_value\")\r\n  |> group()\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Anomalousness changes for all PowerLines over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Results\" or r[\"_measurement\"] == \"Data\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly_value\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"PowerLineID\"])"
    }
   ]
  },
  {
   "title": "Anomalousness changes for all PowerLines over time",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "left = \r\nfrom(bucket: \"Epsymolo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Results\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Anomaly_value\")\r\n  |> group()\r\n  |> keep(columns: [\"PowerLineID\", \"_value\", \"_field\"])\r\n\r\nright = \r\nfrom(bucket: \"Epsymolo\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Results\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"WeekOfYear\")\r\n  |> group()\r\n  |> keep(columns: [\"PowerLineID\", \"_value\", \"_field\"])\r\n\r\nunion(tables: [left, right])\r\n    |> pivot(rowKey: [\"PowerLineID\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n"
    }
   ]
  }
 ]
}