{
 "title": "Sinda's Dashboard",
 "time": { "from": "2023-12-14T23:00:00.000Z", "to": "2023-12-17T22:59:59.000Z" },
 "panels": [
  {
   "title": "Power Change Metrics by Line ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Results\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerChange\")\n  //|> filter(fn: (r) => r[\"PowerLineID\"] == \"0.0\" or r[\"PowerLineID\"] == \"1.0\" or r[\"PowerLineID\"] == \"2.0\")  // Add more IDs as needed\n"
    }
   ]
  },
  {
   "title": "Alerts for Significant Changes in Power Flow",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 }
  },
  {
   "title": "Mean Power Fluctuations Over Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Results\")\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerChange\")\n  |> group(columns: [\"PowerLineID\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Significant Power Change Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"Epsymolo\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Results\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Predicted_IsSignificantChange\")\n  |> group()\n"
    }
   ]
  }
 ]
}